In [1]:
import numpy

In [2]:
numpy.__version__

'1.20.1'

In [3]:
import numpy as np

In [5]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [6]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
a[-1]

array([ 9, 10, 11, 12])

In [9]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [12]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [13]:
np.array(6)

array(6)

In [15]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [16]:
a = np.array([1,2,3])

In [17]:
a

array([1, 2, 3])

In [18]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [19]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [20]:
print(np.arange(4))

[0 1 2 3]


In [21]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [22]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

In [23]:
arr = np.array([1,2,3,4,5,6,7,8])

In [25]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [26]:
np.delete(arr,1)

array([1, 3, 4, 5, 6, 7, 8])

In [27]:
arr = np.array([2,1,5,3,7,4,6,8])

In [28]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
array_example = np.array([[[0,1,2,3],
                           [4,5,6,7]],
                         [[0,1,2,3],
                          [4,5,6,7]],
                         [[0,1,2,3],
                          [4,5,6,7]]])

In [30]:
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [31]:
array_example.ndim

3

In [32]:
array_example.size

24

In [33]:
array_example.shape

(3, 2, 4)

In [34]:
arr_one = np.array([[1,2,3,4,5]])

In [35]:
arr_one.ndim

2

In [36]:
arr_one.shape

(1, 5)

In [37]:
a = np.arange(6)

In [38]:
print(a)

[0 1 2 3 4 5]


In [39]:
b = a.reshape(3,2)

In [40]:
print (b)

[[0 1]
 [2 3]
 [4 5]]


In [41]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [42]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [43]:
a2 = a[np.newaxis]
a2.shape

(1, 6)

In [44]:
a2[0][0]

1

In [45]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [46]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [47]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [48]:
b = np.expand_dims(a, axis=1)

In [49]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [50]:
c = np.expand_dims(a, axis=0)
c

array([[1, 2, 3, 4, 5, 6]])

In [51]:
c.shape

(1, 6)

In [55]:
data = np.array([1,2,3])

In [56]:
data[-2:]

array([2, 3])

In [88]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [58]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
a[a>=5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [60]:
five_up = (a>=5)

print(a[five_up])
print(a[a >= 5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [63]:
10%4

2

In [64]:
10/4

2.5

In [65]:
10/3

3.3333333333333335

In [67]:
1%2

1

In [66]:
a[a%2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [68]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
a[(a > 2) | (a < 11)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# # Creating Array from Existing Data ##

In [70]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [71]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [73]:
a_1 = np.array([[1,1],
                [2,2]])

a_2 = np.array([[3,3],
                [4,4]])

In [74]:
a_1

array([[1, 1],
       [2, 2]])

In [75]:
a_2

array([[3, 3],
       [4, 4]])

In [76]:
np.vstack((a_1, a_2))
ex

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [80]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [81]:
arr_split = np.array([[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,]])

In [82]:
arr_split

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [84]:
x, y, z = np.hsplit(arr_split, 3)

In [85]:
x

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [86]:
y

array([[ 9, 10, 11, 12, 13, 14, 15, 16]])

In [87]:
z

array([[17, 18, 19, 20, 21, 22, 23, 24]])

In [89]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [91]:
b =a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [92]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Basic operation

In [93]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [94]:
a.sum()

10

In [95]:
b = np.array([[1,1],
             [2,2]])

b

array([[1, 1],
       [2, 2]])

In [96]:
b.sum(axis=0)

array([3, 3])

In [97]:
b.sum(axis=1)

array([2, 4])

In [98]:
data = np.array([1,2])
data

array([1, 2])

In [100]:
ones = np.ones (2)
ones

array([1., 1.])

In [103]:
data + ones

array([2., 3.])

In [104]:
data * data

array([1, 4])

In [105]:
data / data

array([1., 1.])

## Broadcasting 

In [106]:
data

array([1, 2])

In [107]:
data.sum()

3

In [108]:
np.array([[0.45004040, 0.17296777, 0.34376245, 0.5510652],
         [0.5462154, 0.05090978, 0.400675840, 0.55645993],
         [0.12697628, 0.82482560, 0.26590556, 0.5691701]])

array([[0.4500404 , 0.17296777, 0.34376245, 0.5510652 ],
       [0.5462154 , 0.05090978, 0.40067584, 0.55645993],
       [0.12697628, 0.8248256 , 0.26590556, 0.5691701 ]])

In [109]:
A = np.array([[0.45004040, 0.17296777, 0.34376245, 0.5510652],
         [0.5462154, 0.05090978, 0.400675840, 0.55645993],
         [0.12697628, 0.82482560, 0.26590556, 0.5691701]])

In [110]:
A.sum()

4.858974310000001

In [111]:
A.min()

0.05090978

In [112]:
A.max()

0.8248256

In [113]:
A.min(axis=0)

array([0.12697628, 0.05090978, 0.26590556, 0.5510652 ])

In [114]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.8248256 ])

In [115]:
A

array([[0.4500404 , 0.17296777, 0.34376245, 0.5510652 ],
       [0.5462154 , 0.05090978, 0.40067584, 0.55645993],
       [0.12697628, 0.8248256 , 0.26590556, 0.5691701 ]])

In [116]:
A.std()

0.21390864016074293

## Matrices

In [117]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [118]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [119]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [120]:
np.random.random((3,2))

array([[0.63055047, 0.1987868 ],
       [0.49346464, 0.27831834],
       [0.01938646, 0.00400646]])

In [127]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.35887461 0.37733194]
 [0.94131562 0.754222  ]
 [0.92779776 0.84599971]]


In [128]:
data = np.array([[1,2], [3,4]])
print(data)

[[1 2]
 [3 4]]


In [130]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [131]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [133]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [134]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


In [135]:
a_1 = np.array([[1,2,3], [4,5,6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7,8], [9,10], [11,12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [136]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [137]:
data = np.array([[1,2], [3,4], [5,6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


In [138]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [139]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [141]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


In [142]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [143]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [144]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [145]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [146]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [150]:
arr = np.arange(6).reshape((2,3))
print(arr)

[[0 1 2]
 [3 4 5]]


## N-Dimensional Array

In [155]:
ndarr = np.array([[[1,2], [3,4]],
                  [[5,6], [7,8]]])

In [156]:
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [157]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [158]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [159]:
print(np.random.random((4,3,2)))

[[[0.62566888 0.95429233]
  [0.5459744  0.77013307]
  [0.62091146 0.60828154]]

 [[0.08558515 0.37436594]
  [0.34246807 0.05312276]
  [0.75711551 0.4209178 ]]

 [[0.06166838 0.20806067]
  [0.43506815 0.33046641]
  [0.90095476 0.00212371]]

 [[0.53079861 0.8296883 ]
  [0.10309413 0.00105274]
  [0.75245612 0.92572978]]]


In [162]:
arrflat = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [163]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Working with math formulas

In [164]:
observed = np.random.random((3,2))
prediction = np.random.random((3,2))

In [165]:
observed

array([[0.83992959, 0.90003346],
       [0.21090206, 0.66132439],
       [0.91494139, 0.6733165 ]])

In [166]:
prediction

array([[0.88322513, 0.22592728],
       [0.45165091, 0.39350922],
       [0.93746463, 0.59444057]])

In [170]:
observed.size

6

In [168]:
(1/observed.size) * np.sum(np.square(observed - prediction))

0.09878455558402062

In [173]:
n = observed.size

error = (1/n) * np.sum(np.square(observed - prediction))

In [174]:
error

0.09878455558402062